apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: my-app
  name: config
spec:
  vaultAuthRef: vault-local
  mount: secret
  type: kv-v2
  name: my-app/config
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: my-app
  destination:
    create: true
    name: config
