apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dexidp

resources:
  - ../../base/dex
  - certificate.yaml
  - ingress.yaml

secretGenerator:
  - name: dex
    options:
      disableNameSuffixHash: true
    files:
      - configuration/config.yaml
